<?= 'index' ?>
<div>
	<a style="margin-top: 20px" class="btn btn-primary" href="<?= $this->url('user', ['action' => 'logout']) ?>">Logout</a>
</div>
<div>
	<a style="margin-top: 20px" class="btn btn-primary" href="<?= $this->url('user', ['action' => 'createUser']) ?>">create new user</a>
	<a style="margin-top: 20px" class="btn btn-primary" href="<?= $this->url('user', ['action' => 'dashboard']) ?>">dashboard</a>
	<a style="margin-top: 20px" class="btn btn-primary" href="<?= $this->url('user', ['action' => 'reports']) ?>">reports</a>
	<a style="margin-top: 20px" class="btn btn-primary" href="<?= $this->url('user', ['action' => 'configuration']) ?>">configuration</a>
</div>