<?php

$title = 'Registration';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$login = $form->get('username');
$login->setAttribute('class', 'form-control');
$login->setAttribute('placeholder', 'enter username');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'enter password');

$confirm = $form->get('cofirmpassword');
$confirm->setAttribute('class', 'form-control');
$confirm->setAttribute('placeholder', 'confirm password');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', ['action' => 'registration']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($login) ?>
    <?= $this->formElement($login) ?>
    <?= $this->formElementErrors()->render($login, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($confirm) ?>
    <?= $this->formElement($confirm) ?>
    <?= $this->formElementErrors()->render($confirm, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();